version: '2'
services:
  worker:
    build: .
    volumes:
      - .:/code
    environment:
      - HOST_IP=${HOST_IP}
      - SERVICE_NAME=EmailWorker
      - STAGE=${STAGE}
    extra_hosts:
      - "cdsp.digitalfunk.io:${HOST_IP}"
