version: '3'
services:
  worker:
    build: .
    volumes:
      - /code
    environment:
      - HOST_IP=${HOST_IP}
      - SERVICE_NAME=WebWorker
      - STAGE=${STAGE}
      - CONFIG_HOST=${CONFIG_HOST}
      - CONFIG_PORT=${CONFIG_PORT}
    extra_hosts:
      - "redis.digitalfunk.io:${REDIS_HOST_IP}"
      - "etcd.digitalfunk.io:${ETCD_HOST_IP}"
