version: '3'

services:
    worker:
        image: mdnwebworker_worker
        volumes:
            - /code
        environment:
            - HOST_IP=${HOST_IP}
            - REDIS_HOST_IP=${REDIS_HOST_IP}
            - DISCOVERY_HOST_IP=${DISCOVERY_HOST_IP}
            - ETCD_HOST_IP=${ETCD_HOST_IP}
            - SERVICE_NAME=EmailWorker
            - STAGE=${STAGE}
            - CONFIG_HOST=${CONFIG_HOST}
            - CONFIG_PORT=${CONFIG_PORT}
        extra_hosts:
            - "redis.digitalfunk.io:${REDIS_HOST_IP}"
            - "etcd.digitalfunk.io:${ETCD_HOST_IP}"
            - "discovery.digitalfunk.io:${DISCOVERY_HOST_IP}"
networks:
    back-tier:
        external: true